<?php

namespace app\modules\user;

/**
 * user module definition class
 */
class Module extends \yii\base\Module
{
    /**
     * {@inheritdoc}
     */
    public $controllerNamespace = 'app\modules\user\controllers';

    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();

        // custom initialization code goes here
    }

    public function beforeAction($action)
    {
        if(\Yii::$app->user->getIsGuest()){
            \Yii::$app->response->error(ERROR_NOT_LOGIN);
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
